apiVersion: v1
kind: Service
metadata:
  name: falco-event-ingestor
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: ingestor
    port: 3200
    targetPort: 3200
  selector:
    app: falco-event-ingestor
  sessionAffinity: None
  type: ClusterIP
